name: dnn
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - numpy
  - scipy
  - pandas
  - sphinx # documentation
  - jupyter_contrib_nbextensions
  - ipywidgets # interactivity
  - plotly
  - plotly-orca # saving plotly
  - psutil # saving plotly
  - matplotlib
  - nibabel
  - jupyterlab
  - boto3
  - cudatoolkit #=9.0
  - torchvision #=0.5.0
  - pillow #=6.2.1
  - libgcc
  - pip
  - pip:
    - sklearn
    - sphinx_rtd_theme
    - opencv-python
