name: dnn-cluster
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - python
  - pytorch=1.1.0
  - torchvision=0.3.0
  - numpy
  - scipy
  - pandas
  - plotly
  - plotly-orca # saving plotly
  - psutil # saving plotly
  - matplotlib
  - nibabel
  - jupyterlab
  - boto3
  - cudatoolkit=9.0
  - torchvision #=0.5.0
  - pillow #=6.2.1
  - libgcc
  - pip
  - pip:
    - sklearn
    - sphinx_rtd_theme
    - opencv-python
