name: dnn-cluster
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - psutil
  - pytorch=1.1.0
  - torchvision=0.3.0
  - cudatoolkit=9.0
  - pillow=6.2.1
  - nibabel
  - jupyterlab
  - boto3
  - libgcc
  - pip
  - pip:
    - sklearn
    - sphinx_rtd_theme
    - opencv-python
    - scikit-image
    - dipy

