name: dnn
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - psutil
  - pytorch
  - torchvision
  - cudatoolkit
  - pillow
  - nibabel
  - boto3
  - libgcc
  - sphinx # documentation
  - pip
  - pip:
    - sklearn
    - sphinx_rtd_theme
    - opencv-python
    - scikit-image
    - dipy
    - vtk=8.2.0
    - fury
    - dipy


